### ISSUE TITLE
getting Cortex M3 legacy target in uVision

### ISSUE THREAD

**Issue by bionic24** [EmanuelFeru/hoverboard-sideboard-hack-GD#1]
Here is a picture of the Windgoo sensorboard that was inside my Hoverboard. The SWD programming pins are directly below the connector for the mainboard. I have measured the pins and added them to the picture. 
![Windgoo_Hoverboard_GD_sensorboard-SWD-programming](https://user-images.githubusercontent.com/3235160/74191616-3b0ea200-4c54-11ea-9e19-9e4319f21c9d.jpg)

Connecting the board through ST-Link utility and unlocking the flash went okay. No errors.

After that I tried to install uVision and open the .UVPROJ file but I get a lot of errors about missing files for the M3 Cortex boards. Probably the custom algorithm for the flashing utility. I have tried to install the legacy database but not sure what to do next. 

The Hex file that is already in the build folder of the repository doesn't flash with ST-Link utility. Is it possible to get a pre-build bin file of the Hoverboard version?

**Comment by EFeru** [comment]
Wow, your board looks different but maybe the pinout is the same.

Does it have the same GD32 MCU as in my repo? I am surprised  it doesn't compile the project. It should be all contained...  try  installing the GD32F130 family of devices.
I will check if I can generate a bin  file from my uVision.  

Edit: apparently is possible to convert the .axf file into .bin. Check 
https://www.silabs.com/community/mcu/32-bit/forum.topic.html/how_to_create_binary-CE0p
Can you give it a try?

**Comment by bionic24** [comment]
Chipset appears to be the same GD32F130 and MPU6052.

The problem is probably due to me having missing libraries or wrong settings. I have never used uVision up until now and tbh it is kind of a pain in the behind to install Keil MDK and spending hours on getting a bin file without succes. 

![Windgoo-chipset](https://user-images.githubusercontent.com/3235160/74200967-a4001500-4c68-11ea-8bd9-556752121f31.jpg)

**Comment by EFeru** [comment]
I managed to generate the .bin file with the steps from [here](http://www.keil.com/support/docs/3213.htm). Try to see if you can flash. You can find the .bin file here:
https://github.com/EmanuelFeru/hoverboard-sideboard-hack-GD/tree/master/build/VARIANT_DEBUG
_______________

Regarding Keil, I installed Keil some time ago and I followed these steps:
https://www.rcgroups.com/forums/showthread.php?2512604-Eachine-H8-mini-acro-firmware

Additionally, I installed the AddOns, in my repo here:
https://github.com/EmanuelFeru/hoverboard-sideboard-hack-GD/blob/master/docs/GD32F1x0_Addon_V3.1.0.rar

If you have time, you can try it. Eventualy these steps will help others as well. I will uptade the ReadMe once we have the steps sorted-out.
If still no success, I will install Keil on my wife's PC which is programming tools free :) to get the installation steps.
______________

EDIT: Feel free to join the **Telegram group** for more Info and insights of other projects:
https://t.me/joinchat/BHWO_RKu2LT5ZxEkvUB8uw
______________

**Comment by bionic24** [comment]
I think this might be thing with my board and not with the file. I can remove the protection, I can read the chip, I can erase the data. But upon writing I get a constant error on 0X8000000. 

12:38:09 : STM32CubeProgrammer API v2.3.0
12:38:12 : ST-LINK SN : 54FF6C064975525024412467
12:38:12 : ST-LINK FW : V2J34S7
12:38:12 : Voltage : 3.26V
12:38:12 : SWD freq : 4000 KHz
12:38:12 : Connect mode: Normal
12:38:12 : Reset mode : Software reset
12:38:12 : Device ID : 0x410
12:38:13 : UPLOADING OPTION BYTES DATA ...
12:38:13 : Bank : 0x00
12:38:13 : Address : 0x4002201c
12:38:13 : Size : 8 Bytes
12:38:13 : Bank : 0x01
12:38:13 : Address : 0x1ffff800
12:38:13 : Size : 16 Bytes
12:38:13 : UPLOADING ...
12:38:13 : Size : 1024 Bytes
12:38:13 : Address : 0x8000000
12:38:13 : Read progress:
12:38:13 : Data read successfully
12:38:13 : Time elapsed during the read operation is: 00:00:00.008
12:38:35 : Memory Programming ...
12:38:35 : Opening and parsing file: debugtestsideboard11feb.bin
12:38:35 : File : debugtestsideboard11feb.bin
12:38:35 : Size : 87153 Bytes
12:38:35 : Address : 0x08000000
12:38:35 : Erasing memory corresponding to segment 0:
12:38:35 : Erasing internal memory sectors [0 85]
12:38:35 : Download in Progress:
12:38:36 : Error: failed to download Segment[0]
12:38:36 : Error: failed to download the File
12:38:36 : Time elapsed during download operation: 00:00:01.034

**Comment by EFeru** [comment]
Can you try locking and then unlocking again the GD32? I had some strange behavior with one board and did the lock/unlocking with all the "Use configuration option bytes" checked (see [here](https://raw.githubusercontent.com/EmanuelFeru/hoverboard-firmware-hack-FOC/master/docs/pictures/unlock_mcu_3.png), just check all boxes, leave the Pages unchecked).
[How-to-Unlock-MCU-flash](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/How-to-Unlock-MCU-flash)

Then it worked well. In my case I could flash it but it was behaving strange. Locking/Unlocking did the job.

**EDIT:** Aa, I see you use STM32CubeProgrammer API. I don't know if that makes a difference, but I used [ST-Link Utility](https://www.st.com/en/development-tools/stsw-link004.html)

**Comment by EFeru** [comment]
@bionic24 I have the same Error if I try to flash with ST Link Utility. Apparently ST Link Utility is not able to flash the device.
Finally, I figured out how to build with Platformio see [build-gd32-project-with-platformio](https://community.platformio.org/t/build-gd32-project-with-platformio/11944)
The guys from Platformio were extremely helpful and now I have a project that runs with Platformio too. I will commit soon. Then you can give it another try.

**Comment by EFeru** [comment]
Platformio committed, check the steps in ReadMe.
Other than that, I installed Keil uVision on a fresh PC and loaded the project. After accepting the installation of the missing packages, the project built without any issues, 0 Errors, 0 Warning. So, for me Keil worked without any hiccups.

**Comment by bionic24** [comment]
Succes!

Platformio opens the project and makes the builds without errors. The original sideboard from the first post still gave me the same issue. After that I tried the right side sideboard. It is equipped with a BT module but the same otherwise. That board was able download the builds. So I probably have a hardware failure in the first board.

Hope to get some testing done this weekend. I probably need to disable the steering value in the FOC firmware to disable it? I have both motors bolted together in the rim of my Onewheel so it is mandatory that they operate exactly the same.
![sideboard-with-bt](https://user-images.githubusercontent.com/3235160/74522887-60cdcc80-4f1c-11ea-857a-8fd7c269159f.jpg)
![a65d2c9fcee4e0ba994685161cdbf001088f7755_2_1035x582](https://user-images.githubusercontent.com/3235160/74522950-7c38d780-4f1c-11ea-9780-487002f1f454.jpeg)

**Comment by EFeru** [comment]
Yes, you will need to disable Steering, check the HOVERCAR variant to see how is done.
