### ISSUE TITLE
GD32F103C8T6 vs GD32F130C6T6

### ISSUE THREAD

**Issue by sdegeorgio** [EmanuelFeru/hoverboard-sideboard-hack-GD#15]
Hi Emanuel,

I have two sets of sideboards one of each shown below.  One set has GD32F103C8T6 and the other set has GD32F130C6T6.

Programming the GD32F130C6T6 fails usually after writing somewhere between 4 and 12 pages and this is consistent for both sideboards in the pair. They unlock and erase / erase verify ok. I think there was another issue already open where people had experienced the same problem but no solution yet.

Programming the GD32F103C8T6 boards always succeeds, however the code does not appear to run properly, LED 4 or 5 turns on and nothing further happens, no communication with main board. Have you ever successfully run on this MCU? I suppose it is not working because of unsupported MPU 6052C?

Do you have any experience with either of these issues or any idea where to start to look to debug?

GD32F103C8T6
![3386EF03-9248-498A-8F05-9B113BEACDD1](https://user-images.githubusercontent.com/24863816/119569020-15a09b80-bda6-11eb-87da-489e76e3c4da.jpeg)

MPU appears to be 6052C.
![5DFC246C-2A03-460C-BCCF-AE7E7133AD1F](https://user-images.githubusercontent.com/24863816/119609587-bebfb400-bdef-11eb-9a68-b30db7bdfecd.jpeg)

GD32F130C6T6
![8FBAD1E2-CC0D-4C6E-9AA1-EE4906DBE2F4](https://user-images.githubusercontent.com/24863816/119569036-1a654f80-bda6-11eb-9cca-2f53e4a368f7.jpeg)

MPU is 6050.
![81377D00-1E1C-4715-B1B8-E2A2A88F2D9F](https://user-images.githubusercontent.com/24863816/119609807-178f4c80-bdf0-11eb-91b7-88ca2e718de1.jpeg)

**Comment by Candas1** [comment]
Hi, 

Sorry I just saw that issue now:
For the 130C6T6 board, can you try to set WDG_SW in [option bytes](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/How-to-Unlock-MCU-Flash) ? 

For the 103C8t6, can you try the STM fork ?

**Comment by sdegeorgio** [comment]
Wow, thank you so much!  Your solution for each respective sideboard worked!

I searched the web for so long before opening the ticket and you solved it so quickly.

Stephan.
