### ISSUE TITLE
region `FLASH' overflowed by 44 bytes

### ISSUE THREAD

**Issue by davidrib** [EmanuelFeru/hoverboard-sideboard-hack-GD#18]
Could someone help-me here?? Exceeds 44 bites :(((((((
I'm not a strong programmer, with any change.
![error](https://user-images.githubusercontent.com/13451945/143778643-092e8c80-f3d5-4176-9fd7-ed1cb454e474.png)
 
The others are OK:
![error2](https://user-images.githubusercontent.com/13451945/143778832-6f74a2a6-da9b-47cf-ad40-dbb35bd7c7e9.png)

**Comment by davidrib** [comment]
My chip version is GD32F130C6 and I have more two boards with GD32F130C8, not tested yet but should work they have more memory, even so, only because 44 Bites is not possible adapt the firmware to fit in 32K ?? I'm not a big programmer but culd someone help?

**Comment by davidrib** [comment]
Success shortened some console messages
![error3](https://user-images.githubusercontent.com/13451945/143779947-33f1486e-463a-405f-a2d5-1c6d99d636fe.png)
I think the project  could be updated 
Thanks

**Comment by EFeru** [comment]
Maybe we could use a define to enable/disable all Debug messages.

**Comment by davidrib** [comment]
> Maybe we could use a define to enable/disable all Debug messages.

I'm not a advanced programmer is the first time I use platforio, but I'm wondering if the compiled version has or not debugging information to start/stop add breackpoints  to some debugger that could be disabled? Should save a lot of space?
(Sorry my bad English)

**Comment by davidrib** [comment]
Done! 35% free space!

![error4](https://user-images.githubusercontent.com/13451945/143887013-1df9c8b8-4b61-4635-932b-e3e7761e9b58.png)

**Comment by davidrib** [comment]
> Maybe we could use a define to enable/disable all Debug messages.

I'm so 🥇 dumb 🥇  :((((((((

Sorry

**Comment by EFeru** [comment]
https://github.com/EFeru/hoverboard-sideboard-hack-GD/blob/50fa92b606b3ecde737a5f6263beb0faeec166a9/platformio.ini#L47

This just defines the VARIANT_DEBUG macro which is used through out the code. If you comment it out, you will not have debug pieces of code in the compilation. So, it won't be the VARIANT_DEBUG anymore.

I just updated travis build and I also get 44 bytes overflow. I think the new platformio or better said new librarier from platformio use more resources... it happened before.. I will see what can be done soon.

**Comment by maxgerhardt** [comment]
44 bytes oversize is really on the edge. I know it built before with an earlier version of my platform-gd32. So, if new features aren't needed and rather, stability is needed, I can do a PR for the `platformio.ini` to use fixed git commit hashes that results in a good build. 

(But then possible new features in platform-gd32 can't be taken advantage of) 

This problem was foreshadowed in https://github.com/EFeru/hoverboard-sideboard-hack-GD/pull/16.

**Comment by maxgerhardt** [comment]
I've proposed a fix for it in https://github.com/EFeru/hoverboard-sideboard-hack-GD/pull/19.
