### ISSUE TITLE
Help with this board

### ISSUE THREAD

**Issue by krisstakos** [EmanuelFeru/hoverboard-sideboard-hack-GD#20]
So I've cracked an old hoverboard containing these identical 2 pcbs. It uses GD32F130C6T6 (reports 32k, I was able to upload the whole bin file, I had to hold the power button during flash)
And I was able to compile & flash the DEBUG example without the MPU_SENSOR definition
![IMG_20220404_194632](https://user-images.githubusercontent.com/5090779/161634455-b0a4de99-0762-4e45-b032-401ed265a3f9.jpg)

Any help of the pinout of where is that UART that I can hook and observe/send commands?
One additional question - with that VARIANT_DEBUG can I send commands to move the motor? and what I should use if that's not the right variant (not interested in MPU sensor just sending command to move in specified direction and speed)

**Comment by Candas1** [comment]
Hi, 

You are posting in the wrong repository, this firmware is for sideboards, those have no motor control.
Please check [here](https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Firmware-Compatibility)

**Comment by krisstakos** [comment]
Hi, you are right it's for sideboards(with integrated mosfets). But the board chip is GD32F130C6T6 and I didn't find any reference there. It looks like to me that's a mix between the two. Hardware wise is 90% like in the url you mentioned but as I said there is no c6 version is it possible to flash the c8?

**Comment by Candas1** [comment]
Well the wiki is made to point you in the right direction, your need to look for help in those repositories or in the telegram group.

Are you sure you are reading the chip model well ?

**Comment by krisstakos** [comment]
Well I'm 100% sure it's GD32F130**C6**T6 (previously wrote it 103 by mistake, but searching through the repos for F130**C6**) Okay I will try searching help else where. Thanks

**Comment by Candas1** [comment]
That's my point
You are asking for help about the wrong chip in the wrong repository 🤣
Have you seen [this](https://github.com/flo199213/Hoverboard-Firmware-Hack-Gen2/issues/13) ?

**Comment by krisstakos** [comment]
That looks promising I guess. Thanks!
