### ISSUE TITLE
Firmware.bin Will Not Flash

### ISSUE THREAD

**Issue by 1BadAz** [EmanuelFeru/hoverboard-sideboard-hack-GD#21]
I tried forking the code and when I try and upload firmware.bin it will not download, ST-Link is saying "warning core is locked up." It will download firmware.elf (idk what that is) and when I power the board it beeps in sets of three. I am attempting to use US_ARtT variant. When I hook it to an Arduino it seems to have no effect.

**Comment by krisstakos** [comment]
You have to unlock your chip first: https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/How-to-Unlock-MCU-flash

**Comment by 1BadAz** [comment]
I already disabled read-out protection. I have locked and unlocked it a dozen times still no change. I also did follow the step in that link to check all of the user config options. There is still no change.

**Comment by 1BadAz** [comment]
Now saying"Error: Mass erase operation failed. Please verify flash protection.
