### ISSUE TITLE
Disable WDG_SW for correct operation.

### ISSUE THREAD

**Issue by AlexJenjer** [EmanuelFeru/hoverboard-sideboard-hack-GD#26]
Disable WDG_SW for correct operation. Put a tick in the options in the programmer ST-LINK.  It took a lot of effort to solve the problem.

**Comment by AlexJenjer** [comment]
чч

**Comment by Candas1** [comment]
Hi
It's also written in the wiki

**Comment by AlexJenjer** [comment]
It's not obvious !
