### ISSUE TITLE
GD32F130C8T6

### ISSUE THREAD

**Issue by tonvanhieu** [EmanuelFeru/hoverboard-sideboard-hack-GD#3]
My sideboard chipset is GD32F130C8T6 different from yours (C6T6). I have flashed your firm ware to my chip success but it can't read MPU data. Do you know  what i  have to do to make project is suitable with C8T6 chip

**Comment by EFeru** [comment]
Looking at the memory map [GD32F130C8T6](https://datasheet4u.com/datasheet-parts/GD32F130C8T6-datasheet.php?id=976683) vs [STM32F103C8T6](https://github.com/EmanuelFeru/hoverboard-sideboard-hack-STM/blob/master/docs/stm32f103c8-Datasheet.pdf)  there are similarities but also differences. So, I don't think the [hoverboard-sideboard-hack-STM](https://github.com/EmanuelFeru/hoverboard-sideboard-hack-STM) version would match.

I think you need to download the `GD32F1x0_Firmware_Library_V3.1.0` from here:
https://gd32mcu.21ic.com/documents
search for `GD32F1x0` and download the files. Then replace the library.

In quick words these should be the steps. Let me know about the progress.

![image](https://user-images.githubusercontent.com/24780745/75229504-516b4080-57b2-11ea-9b63-94ab646a53ea.png)

**Comment by EFeru** [comment]
oh, I just noticed is the same GD library, the C8T6 has only more memory (Flash: 64K, Ram: 8K ) than the C6T6 (Flash: 32K, Ram: 4K).
After flashing, does the LEDs blink? 

Edit: Can you check the connection of I2C_SDA and I2C_SCL pins from MPU6050 towards the GD32? Which pins of the GD32 are used for that?

**Comment by tonvanhieu** [comment]
I'm checking it.
I just change device from device list and the "Programming Algorithm" then I can flash it normally. But i have problem with debugging by Keil 5. Variables that i add to WATCH window don't change, it's always ZERO.
Yes, the center LEDs blink.
I have checked I2C, it's same as yours ( I2C_0, PB6 and PB7). Because i can't debug so i don't know if it can read or not ( i will check it by USART later).

**Comment by EFeru** [comment]
That is a good sign! And do you get Green LED after the blink? That is an indication the MPU6050 is working fine.
Edit: For debugging and playing with the board a bit you need one of [this](https://www.banggood.com/FT232RL-FTDI-USB-To-TTL-Serial-Converter-Adapter-Module-p-917226.html). I heard someone did it with an ESP32, maybe an Arduino also works... basically you need a Serial Communication, but this you know :)

**Comment by tonvanhieu** [comment]
I will check it later ( i have to go to school now). 
By the way my MPU  is 6052, is it same with 6050?

Reply edit: yeah i know about that, in my case i use my USART-Bluetooth module (HC-05 - from my old project 😄 ).

**Comment by EFeru** [comment]
MPU6052 is probably a newer variant, theoretically it should work, practically I didn't check because I don't have it.

**Comment by tonvanhieu** [comment]
BIG PROBLEM WITH DELAY FUNCTION.
It's always stuck when meet delay(>400). I don't know why.  When i delete introDemoLED(100); it configuring MPU non-stop.
![image](https://user-images.githubusercontent.com/61009690/75318572-4e994a00-589d-11ea-8137-c2be28af11fb.png)
Edit: Do i need power the board by 15V to enable MPU???

**Comment by EFeru** [comment]
You need to power the board with at least 12V. I noticed similar funny behavior when I was powering the board with 7.5V from an external source.
So, yes, either use the an external source with 12V or use the mainboard power.

**Comment by tonvanhieu** [comment]
delay_ms(); make program be stuck. How to fix it :((. i feel so impotent.
I have tried power it by mainboard but nothing change.
Sensors work well but mpu not yet.

**Comment by tonvanhieu** [comment]
It's all about delay function. when i change delay time in mpu_init() below 10 the board can go 1 more step (writing DMP). So, if i can find out what happen to delay_ms() i can solve that. But i still can't :((. Delay_ms() kill me.
![image](https://user-images.githubusercontent.com/61009690/75340250-bca53780-58c4-11ea-93cc-5a1dbf1e439d.png)

**Comment by EFeru** [comment]
How did you unlock your GD32 chip? 

I had similar behavior with one board. To fix it I did the following (please try):
* Lock back the GD32 with ST Link Utility
* Unlock the GD32 as described [here](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/How-to-Unlock-MCU-Flash) 
* At Step 6, check all the boxes for "User configuration option bytes"
* Flash and try

**Comment by tonvanhieu** [comment]
I follow you at step 6 and this box appear
![image](https://user-images.githubusercontent.com/61009690/75346543-81f5cc00-58d1-11ea-9138-5bc0aa97333b.png)
Any wrong with it?
EDIT: OH MY GODDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.
It WORKS. OMG. YOU ARE GOD. 
Let me call you teacher from now. You teach me so much.

**Comment by EFeru** [comment]
Hahaha...:) Good that it works. The error is no issue.
Yeah.. sometimes the unlocking is not done properly and you get funny behavior.

EDIT: I will put this as a side note in the unlocking process. If someone else has the same issue.

**Comment by Nassimraz** [comment]
Hello my board with gd32 turned off after unlocking mcu ( I didn't hold the power button while unlocking)

**Comment by AndresHernandez15** [comment]
> I follow you at step 6 and this box appear ![image](https://user-images.githubusercontent.com/61009690/75346543-81f5cc00-58d1-11ea-9138-5bc0aa97333b.png) Any wrong with it? EDIT: OH MY GODDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD. It WORKS. OMG. YOU ARE GOD. Let me call you teacher from now. You teach me so much.

I got the same error, can you explain what did you do to solve it?

<img width="502" height="933" alt="Image" src="https://github.com/user-attachments/assets/81364e3f-d5bd-419e-802b-6d1623097378" />

EDIT: pls HELP, I really need this to work and cannot find a way to do it :(

**Comment by fabio-s-franco** [comment]
@AndresHernandez15  The only way I managed to do it was by cutting the trace from BOOT0 pin, because it was tied to ground (preventing entering in bootloader mode).
The reason I went this way is because my best hypothesis was that the firmware was blocking SWDIO protocol on boot.
I then shorted BOOT0 pin to the nearby VDD pin with tweazers and put a jumper in the power button header to keep the board powered. If you hear nothing (no beeping of the board and no magic smoke) you likely succeed in starting in bootloader mode and you can lift the tweazers.
At this point you should be able to flash. Still need to disable read protection in the utility.
Once you flash it, you know longer need to do this as the firmware now won't block SWDIO like with the firmware I had did.
