### ISSUE TITLE
Arduino control

### ISSUE THREAD

**Issue by pav18** [EmanuelFeru/hoverboard-sideboard-hack-GD#7]
Hello.
Would you share a code to control this board via UART?
Thank you.

**Comment by EFeru** [comment]
It is there already there. You just need to send a structure of the following format via UART:
https://github.com/EmanuelFeru/hoverboard-sideboard-hack-GD/blob/c703b309300446bea40bd06d833f206ab9da93ba/Src/main.c#L44-L57

Make sure you send the structure at the Baud rate and Start frame as specified here:
https://github.com/EmanuelFeru/hoverboard-sideboard-hack-GD/blob/c703b309300446bea40bd06d833f206ab9da93ba/Inc/config.h#L69-L70

Of course you can modify the structure to your needs.

**Comment by pav18** [comment]
It looks like feedback structure but how to control sideboard's leds etc?

**Comment by EFeru** [comment]
In the structure, there is `cmdLed`. With this you control the Leds. Each bit represents one Led on (1) and off (0).
